### ISSUE TITLE
Permission denied: '/Library/Python/2.7/site-packages/nose'

### ISSUE THREAD

**Issue by stlandhbb** [jbrew/pt-voicebox#19]
I'm a newbie at this and I just wanted to try out this program, but unfortunately I got stumped in terminal by this error message:
![screen shot 2016-11-12 at 01 49 20](https://cloud.githubusercontent.com/assets/23410777/20234818/4a7c0812-a87a-11e6-906e-25a0de56e053.png)

help would be greatly appreciated

**Comment by pennetti** [comment]
Hey @stlandhbb, thanks so much for submitting this issue. The root cause is actually a security feature in OS X that locks down certain root directories and unfortunately this is where `pip` installs packages by default. This is [well known issue](http://apple.stackexchange.com/questions/209572/how-to-use-pip-after-the-os-x-el-capitan-upgrade) and I'm looking into a workaround for this project that doesn't involve too much terminal usage. In the mean time, could you try adding the `--user` flag to the `pip` install command and let me know if that fixes it for you? The full command would be `pip install --user -r requirements.txt`. Thanks again.

**Comment by stlandhbb** [comment]
It works! Thank you.
